-- Flood Alert schema
-- Paste into Supabase SQL editor and run.

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  email text,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.device_state (
  device_id text primary key,
  water_level int4,
  updated_at timestamptz not null default now()
);

create table if not exists public.sensor_logs (
  id bigint generated by default as identity primary key,
  device_id text not null,
  water_level int4 not null,
  created_at timestamptz not null default now()
);

create unique index if not exists user_profiles_username_lower_unique_idx on public.user_profiles (lower(username)) where username <> '';
create unique index if not exists user_profiles_email_lower_unique_idx on public.user_profiles (lower(email)) where email <> '';
create index if not exists sensor_logs_device_id_idx on public.sensor_logs (device_id);
create index if not exists sensor_logs_created_at_idx on public.sensor_logs (created_at desc);

-- Optional admins table to avoid querying user_profiles within its own RLS policy
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

drop trigger if exists device_state_set_updated_at on public.device_state;
create trigger device_state_set_updated_at
before update on public.device_state
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_profiles (id, email, username)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'username', ''))
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.user_profiles enable row level security;
alter table public.device_state enable row level security;
alter table public.sensor_logs enable row level security;

-- Profiles: users can read/update own, admins can read/update all
drop policy if exists "profiles_select_self" on public.user_profiles;
create policy "profiles_select_self"
  on public.user_profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.user_profiles;
create policy "profiles_update_self"
  on public.user_profiles for update
  using (auth.uid() = id);

drop policy if exists "profiles_admin_all" on public.user_profiles;
create policy "profiles_admin_all"
  on public.user_profiles for all
  using (exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
  ));

-- Device state: registered users (and admins) can read
-- Device state: allow any authenticated user to read
drop policy if exists "device_state_select_registered" on public.device_state;
create policy "device_state_select_registered"
  on public.device_state for select
  using (auth.role() = 'authenticated');

-- Sensor logs: registered users (and admins) can read
-- Sensor logs: allow any authenticated user to read
drop policy if exists "sensor_logs_select_registered" on public.sensor_logs;
create policy "sensor_logs_select_registered"
  on public.sensor_logs for select
  using (auth.role() = 'authenticated');
create or replace function public.get_email_by_username(_username text)
returns text as $$
declare
  _email text;
begin
  select email into _email
  from public.user_profiles
  where lower(username) = lower(_username)
  limit 1;
  return _email;
end;
$$ language plpgsql security definer;

grant execute on function public.get_email_by_username(text) to anon;